# Generated by Django 2.2.12 on 2020-05-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_de_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosuser',
            options={'verbose_name': 'Datos de Usuario', 'verbose_name_plural': 'Información'},
        ),
        migrations.AlterModelOptions(
            name='detaroles',
            options={'verbose_name': 'Detalles del rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidades del Usuario', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Nivel de habilidad', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='descripcionHab',
            field=models.TextField(default='Desarrollador', verbose_name='Descripcion de la habilidad'),
        ),
    ]
