# Generated by Django 2.2.12 on 2020-05-13 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_de_usuario', '0003_auto_20200513_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=100, null=True, verbose_name='Lenguaje')),
                ('motorBD', models.CharField(max_length=155, null=True, verbose_name='Motor de Base de Datos')),
                ('arquitectura', models.CharField(max_length=100, verbose_name='Arquitectura de el software')),
            ],
            options={
                'verbose_name': 'Categoría del Proyecto',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoDocu', models.CharField(max_length=100, verbose_name='Nombre tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=200, null=True, verbose_name='Nombre del proyecto')),
                ('descripcionProy', models.TextField(null=True, verbose_name='Descripción acerca del proyecto')),
                ('imagenProyecto', models.ImageField(default='proyect.png', null=True, upload_to='', verbose_name='Imagen del proyecto')),
                ('fechaInicio', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de inicio del proyecto')),
                ('fechaFin', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de finalizacion del proyecto')),
                ('urlRepositorio', models.TextField(null=True, verbose_name='Ruta del repositorio del proyecto')),
                ('estadoProyecto', models.CharField(max_length=50, null=True, verbose_name='Estado del proyecto')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategoriaProyecto', verbose_name='Identificador de categoria')),
            ],
            options={
                'verbose_name': 'Información del Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDocumento', models.CharField(max_length=255, null=True, verbose_name='Nombre de el documento')),
                ('pathDocumento', models.CharField(max_length=255, null=True, verbose_name='Ruta de el documento')),
                ('idProyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Id del proyecto')),
                ('idTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocumento', verbose_name='Id tipo de documento')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_de_usuario.DatosUser', verbose_name='Id del usuario')),
            ],
            options={
                'verbose_name': 'Documentacion',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
