# Generated by Django 2.2.12 on 2020-05-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='pathDocumento',
            field=models.FileField(upload_to='documentos/proyectos', verbose_name='Archivo'),
        ),
    ]
