# Generated by Django 2.2.12 on 2020-05-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_de_usuario', '0003_auto_20200513_1517'),
        ('proyectos', '0002_auto_20200521_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoproy', models.CharField(max_length=100, verbose_name='Tipo de proyecto')),
                ('lenguaje', models.CharField(max_length=50, verbose_name='Lenguaje Back-End')),
                ('motordb', models.CharField(max_length=50, verbose_name='Motor BD')),
                ('arquitect', models.CharField(max_length=150, verbose_name='Arquitectura')),
            ],
            options={
                'verbose_name': 'Categoria de proyecto',
                'verbose_name_plural': 'Tipo de Proyecto',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombtido', models.CharField(max_length=50, verbose_name='Nombre de tipo de documento')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categoría de Documentos',
            },
        ),
        migrations.AlterModelOptions(
            name='documentos',
            options={'verbose_name': 'Documentos de Proyecto', 'verbose_name_plural': 'Documentos de Proyecto'},
        ),
        migrations.AlterModelOptions(
            name='proyectos',
            options={'verbose_name': 'Proyectos de usuario', 'verbose_name_plural': 'Proyectos y Experiencias'},
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='idProyectos',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='idTipoDocu',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='nombreDocumento',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='pathDocumento',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='descripcionProy',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='estadoProyecto',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='fechaFin',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='fechaInicio',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='imagenProyecto',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='nombreProyecto',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='urlRepositorio',
        ),
        migrations.AddField(
            model_name='documentos',
            name='documento',
            field=models.FileField(null=True, upload_to='documentos/proyectos', verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='idproyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyectos'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='idusuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datos_de_usuario.DatosUser', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='nombdocu',
            field=models.CharField(max_length=256, null=True, verbose_name='Nombre de Documento'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='descproyect',
            field=models.TextField(null=True, verbose_name='Descripción del proyecto'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fechafin',
            field=models.DateField(null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fechaini',
            field=models.DateField(null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='logoproyect',
            field=models.ImageField(null=True, upload_to='img/proyectos', verbose_name='Icono'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='nombproyect',
            field=models.CharField(max_length=256, null=True, verbose_name='Nombre de Proyecto'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='urlrepo',
            field=models.URLField(null=True, verbose_name='Enlace de repositorio'),
        ),
        migrations.DeleteModel(
            name='CategoriaProyecto',
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
        migrations.AddField(
            model_name='documentos',
            name='idtipodocu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='idcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.CateProyecto', verbose_name='Categoría'),
        ),
    ]
